export const contracts: any = {
  //   BRIDGE: "BridgeUpgradeable",
  //   VOTER: "VoterUpgradeable",
  //   ERC20HANDLER: "ERC20HandlerUpgradeable",
  //   FEEMANGER: "FeeManagerUpgradeable",
  //   DFYN: "RouterERC20UpgradableToken",
  //   ROUTE: "RouterERC20UpgradableToken",
  //   ERC20Token: "RouterERC20UpgradableToken",
  //   HANDLERRESERVE: "HandlerReserveUpgradeable",
  //   GENERICHANDLER: "GenericHandlerUpgradeable",
  //   FEEMANAGERGENERIC: "FeeManagerGenericUpgradeable",
  //   SEQUENCER: "SequencerHandlerUpgradeable",
  //   USDCBURNER: "UsdcDepositAndBurn",
  //   USDCMINTER: "UsdcMinter",
};
